#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 28 02:13:33 JST 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim test_dct2_behav -key {Behavioral:sim_1:Functional:test_dct2} -tclbatch test_dct2.tcl -view /home/y/project/array2/test_butterfly_behav.wcfg -view /home/y/project/array2/test_dct2_behav.wcfg -log simulate.log"
xsim test_dct2_behav -key {Behavioral:sim_1:Functional:test_dct2} -tclbatch test_dct2.tcl -view /home/y/project/array2/test_butterfly_behav.wcfg -view /home/y/project/array2/test_dct2_behav.wcfg -log simulate.log

